#Characteristics of Risk-Return Metrics

#In this section, we will simulate equity curves to study the characteristics of risk-return metrics in Table 1-1. This will help us determine which risk-return metrics to focus on when we optimize strategies.

#---------------------------------
#Load libraries

library(quantmod)

#-------------------------------

#Turn off warnings
options("getSymbols.warning4.o" = FALSE, 
"getSymbols.auto.assign" = FALSE)

# Loads S&P 500 ETF data, stores closing prices as a vector

SPY <- suppressWarnings(getSymbols(c("SPY"), from = "2012-01-01"))
SPY <- as.numeric(SPY$SPY.Close)[1:987]

#----------------------------------------------
#Simulating equity curves
#---------------------------------------------

#Set seed
set.seed(123)

#Create Time Index (notice the -1. t starts at 0 here)
t <- 1:(length(SPY)-1)

#Tradable capital vector (money we have to invest)
Vt <- c(rep(10000, length(t)))

#Benchmark return series (rep command is used to replicate a value (x,times) are its input
Rb <- rep(NA, length(t))
for(i in 2:length(t)){Rb[i] <- (SPY[i]/SPY[i-1]) - 1}

#Benchmark Equity Curve
Eb <- rep(NA, length(t))
Eb[1] <- Vt[1]
for(i in 2:length(t)){Eb[i] <- Eb[i-1]*(1+Rb[i])}

#Randomly simulated return series 1

Rt <- rep(NA,length(t))
for(i in 2:length(t)){
Rt[i] <- Rb[i] + rnorm(n = 1,
mean = 0.24/length(t),
sd = 2.5*sd(Rb, na.rm = TRUE))
}

# Randomly Simulated Return Series 2
Rt2 <- rep(NA, length(t)) 
for(i in 2:length(t)){
Rt2[i] <- Rb[i] + rnorm(n = 1,
mean = 0.02/length(t),
sd = .75 * sd(Rb, na.rm = TRUE))
}

# Randomly Simulated Equity Curve 1
Et <- rep(NA, length(t))
Et <- Vt[1]
for(i in 2:length(t)) { Et[i] <- Et[i-1] * (1 + Rt[i]) }

# Randomly Simulated Equity Curve 2
Et2 <- rep(NA, length(t))
Et2 <- Vt[1]
for(i in 2:length(t)) { Et2[i] <- Et2[i-1] * (1 + Rt2[i]) }

#--------------------------------
#Plot of Et1 against the SPY Portfolio
#--------------------------------

plot(y = Et, x = t, type = "l", col = 1,
xlab = "Time",
ylab = "Equity($)",
main = "Figure 1-3: Randomly Generated Equity Curves"
)
grid()
abline(h = 10000)
lines(y = Et2, x = t, col = 2)
lines(y = Eb, x = t, col = 8)
legend(x = "topleft", col = c(1,2,8), lwd = 2, legend = c("Curve 1", "Curve 2", "SPY"))

#==========================================
# Measuring Performance
#==========================================

#After creating our equity curves and our actual market distribution(SPY) we will now try to figure out how our equities are actually performing (risk adjusted). We start with the Sharpe Ratio.

#---------------------------------
#1) Sharpe Ratio
#---------------------------------

#Listing 1-3. High-Frequency Sharpe Ratio

# Use na.rm = TRUE to ignore NAs at position 1 in return series

SR <- mean(Rt, na.rm = TRUE)/sd(Rt, na.rm = TRUE)
SR2 <- mean(Rt2, na.rm = TRUE)/sd(Rt2, na.rm = TRUE)
SRb <- mean(Rb, na.rm = TRUE)/sd(Rb, na.rm = TRUE)

#----------

#Plotting equity curve against performance metric (sharpe ratio)

plot(y = Et, x = t, type = "l", col = 1,
xlab = "",
ylab = "Equity ($)",
main = "Figure 1-4: Sharpe Ratios"
)
grid()
abline(h = 10000)
lines(y = Et2, x = t, col = 2)
lines(y = Eb, x = t, col = 8)
legend(x = "topleft", col = c(1,2,8), lwd = 2,
legend = c(paste0("SR =", round(SR,3)),
paste0("SR = ", round(SR2, 3)),
paste0("SR =", round(SRb, 3))))

#---------------------------

#Maximum Drawdown Ratios

MD <- function(curve, n = 1){
time <- length(curve)
V <- rep(NA, (time*(time-1))/2)
k <- 1
for(i in 1:(length(curve)-1)){
for(j in (i+1):length(curve)){
v[k] <- curve[i] - curve[j]
k <- k+1
}
}

m <- rep(NA, length(n))
for(i in 1:n){
m[i] <- max(v)
v[which.max(v)] <- -Inf
}
return(m)
}

#---------------------------------
#Regression Based Performance Metrics

# Scatterplot of Rt against Rb

plot(y = Rt, x = Rb, pch = 20, cex = 0.5, xlab = "SPY Returns", 
ylab = "return Series 1", main = "Figure 1-7: Return Series 1 vs. SPY"
)

grid()
abline(h = 0)
abline(v = 0)

#Compute and store the regression model

model <- lm(Rt ~ Rb)

#Plot the regression line
abline(model, col = 2)

#Display alpha and beta
legend(x = "topleft", col = c(0,2), lwd = 2, 
legend = c("Alpha Beta R^2",
paste0(round(model$coefficients[1], 4), "",
round(model$coefficients[2], 2), "",
round(summary(model)$r.squared, 2))))

#------------

#We will run the regression again, temporarily adding a small constant to all negative returns to demonstrate how Jensen’s Alpha works.

RtTemp <- c(0, Rt[-1])
RtTemp[RtTemp < 0] <- RtTemp[RtTemp < 0] + 0.01
model <- lm(RtTemp ~ Rb)


plot(y = RtTemp, x = Rb, pch = 20, cex = 0.5, xlab = "SPY Returns", 
ylab = "return Series 1", main = "Figure 1-7: Return Series 1 vs. SPY"
)

grid()
abline(h = 0)
abline(v = 0)

#Compute and store the regression model

model <- lm(RtTemp ~ Rb)

#Plot the regression line
abline(model, col = 2)

#Display alpha and beta
legend(x = "topleft", col = c(0,2), lwd = 2, 
legend = c("Alpha Beta R^2",
paste0(round(model$coefficients[1], 4), "",
round(model$coefficients[2], 2), "",
round(summary(model)$r.squared, 2))))

#We see in Figure 1-8 that Jensen’s Alpha is ten times higher when the strategy is able to reduce the impact of losing days by an average of 1 percent. Jensen’s Alpha will prefer risk management on down days to outperformance on good days. 