#-------------------------------
# SIMULATION AND BACK TESTING
#-------------------------------

#Some Terminologies:

#OPEN will most often be DATA[["Open"]]. This is given as a nontrivial input for cross validation and optimization purposes in Chapter 8. Remember that we trade at the open because of the nature of our data. We gain access to a given day’s closing price at least 15 minutes after the market closes, so the next opportunity we have to trade is the open of the following day.

#• CLOSE will most often be DATA[["Close"]]. Similarly to OPEN, this will be an important input in Chapter 8.

#• ENTRY is a zoo object with the same dimensions as DATA[["Close"]] that specifies which stocks to enter when. A 0 corresponds to no action, a 1 corresponds to long, and a -1 corresponds to short. A stock triggered by ENTRY will have C dollars (K −k) allocated to either the long or short position. If ENTRY denotes more than K stocks should be entered that period, it will pick K stocks according to favorability.

#• EXIT is a zoo object with the same dimensions as DATA[["Close"]] that specifies when to deliberately exit a stock. A 0 corresponds to no action, a 1 corresponds to exiting a long position, a -1 corresponds to exiting a short position, and a 999 corresponds to exiting any position. In every case, the entire position is liquidated. For strategies that only require ENTRY and FAVOR, EXIT can be set to all zeros.

#• FAVOR is a zoo object with the same dimensions as DATA[["Close"]] that specifies the favorability of a given stock at any given time. This is required when ENTRY indicates more than K stocks to enter, and when ENTRY requires some, existing positions must be liquidated in order to avoid owning more than K stocks. A higher value of FAVOR indicates a desirable long position and an undesirable short position. A lower or more negative value of FAVOR indicates a desirable short position or an undesirable long position. Good defaults are mean return and Rolling Sharpe Ratio. It may be of theoretical interest in certain strategies to fill FAVOR with random numbers. Any NA values in FAVOR will be replaced with zeros at the initiation of the simulator. This object is sorted and ordered frequently in the course of simulation, and NA values cannot be handled via default R behavior.

#• maxLookback is the greatest number of periods any indicator looks back in time plus one. This is necessary to ensure matrices are not being processed when they contain all NA values or incomplete computations due to na.rm=TRUE. We typically want to use na.rm=TRUE to allow for maintenance of NA values in our uniform date template data, but we do not want to abuse it to allow computations of SMAt,100 at t=2.

#maxAssets is equal to K, which specifies the greatest number of stocks or unique assets to be held at any given time. Our simulator allows portfolio management with equal allocation of cash between K stocks. It will distribute startingCash among K stocks and then distribute on-hand cash equally between new stocks as the money compounds.

#• startingCash is simply the amount invested initially. It is important to specify a realistic value to each individual to study the interaction between account sizes and commission structures.

#slipFactor is a percentage of slippage to be added to each trade. Slippage is defined as the difference between the price in data and the price in execution not accounting for spreads. Realistically, slippage can work for or against you, but it is necessary to account for a small amount to simulate realistic trading results. We will discuss the degree of slippage that is appropriate for our sample strategies, which will highlight the importance of automation. For this input, 0.001 corresponds to a 0.1 percent handicap in each entry and exit. This will increase the prices when buying and decrease them when selling.

#spreadAdjust is the dollar value to handicap each trade. It works as the dollar-value analog to slipFactor but is most commonly used to adjust for paying the spread in market orders. A value of 0.01 corresponds to a one-cent handicap and is realistic when trading small-dollar volumes on liquid stocks during nonvolatile trading.

#flatCommission is the dollar value of a commission for a single trade of any size. It is incorporated at both entry and exit. If your brokerage offers a $7 flat commission on each trade, 7.00 is the appropriate value. If your brokerage offers a $7 flat commission at only the entry, a value of 3.50 will simulate this properly.

#perShareCommission is the dollar value to handicap the price of each share to simulate the effects of commissions charged on a per-share basis. If the per-share commission is one-half of a cent each way, the proper value is 0.005. At the time of writing, I am unaware of any scenario where the per-share commission is charged on entry only, so one-way per-share commissions are not supported in this function but can be approximated by entering half of the value as in flat commissions.

#verbose is a logical flag indicating whether to output performance information as the function walks through time. We will not use this when running the function through multicore algorithms because the console output is discarded. Some time can be saved reaching the final results by setting this to FALSE.

#failThresh is the dollar value of the equity curve at which to halt the process, returning the incomplete equity curve and a warning message. When testing strategies manually, in a sequential loop, multicore loop, or otherwise, halting failing strategies without throwing errors may help the user save time. It defaults to 0, which is hard to breach because of the geometric nature of compounding, but it is well utilized when set to some fraction of starting cash. There are situations, like during gradient optimization or early exploratory research, where it would be unwise to set this value to something other than zero.

#initP and initp are used during cross validation to pass position and account information across strategy simulations. We will not touch these until the end of Chapter 8.

#equNA is a function used in the data preparation that dynamically enforced maxLookback on stocks that start their S&P tenure in the middle of OPEN and CLOSE.

#----------------------------------
#Listing 7-1: Pseudocode
#----------------------------------

#1. Check that ENTRY, EXIT, and FAVOR match in dimensionality with
#DATA[["Close"]], throwing an error if nonmatching.

#2. Assign account variables based on function inputs. Allocate space for share count matrix P, entry price matrix p, equity curve vector equity, and cash vector C. Note that the share count matrix accounts for shorts with negative share counts.

#3. The walk-through optimization begins. Repeat steps 4 through 12 for each trading day.

#4. Carry over cash and positions from the last period.

#5. Determine which stocks to enter based on ENTRY. If in excess of K, eliminate extras by favorability based on FAVOR.

#6. Determine which stocks to exit by trigger based on EXIT.

#7. Determine whether more stocks must be exited to respect K, the maximum number of assets held at any given time. Determine which of these stocks to exit by favorability based on FAVOR. Stocks that have been marked for exit by the trigger in the previous step cannot also be marked for exit based on favorability.

#8. Finalize the vector of stocks to exit.

#9. Exit all stocks marked for exit.

#10. Enter all stocks marked for entry.

#11. Loop through active positions to determine equity for the period.

#12. If verbose = TRUE, output optimization diagnostics every 21 trading days (about monthly).

#13. Return the equity curve, cash vector, share count matrix, and entry price matrix.

#---------------------
#library
library(zoo)

#load data
load("~/Desktop/Finance/Automated Systems/Code for R/Platform/functions/Environment6.RData")

#Listing 7-1: Simulating Performance

equNA <- function(v){
o <- which(!is.na(v))[1] 
return(ifelse(is.na(o), length(v)+1, o))
}

simulate <- function(OPEN, CLOSE,
                     ENTRY, EXIT, FAVOR,
                     maxLookback, maxAssets, startingCash,
                     slipFactor, spreadAdjust, flatCommission, perShareCommission, verbose = FALSE, failThresh = 0,
                     initP = NULL, initp = NULL){
                     
# Step 1
if( any( dim(ENTRY) != dim(EXIT) ) | 
any( dim(EXIT) != dim(FAVOR) ) |
any( dim(FAVOR) != dim(CLOSE) ) | 
any( dim(CLOSE) != dim(OPEN)) )
stop( "Mismatching dimensions in ENTRY, EXIT, FAVOR, CLOSE, or OPEN.")

if( any( names(ENTRY) != names(EXIT)) |
any( names(EXIT) != names(FAVOR) ) |
any( names(FAVOR) != names(CLOSE) ) |
any( names(CLOSE) != names(OPEN) ) | is.null(names(ENTRY)) | is.null(names(EXIT)) | is.null(names(FAVOR)) | is.null(names(CLOSE)) | is.null(names(OPEN)) ) 
stop( "Mismatching or missing column names in ENTRY, EXIT, FAVOR, CLOSE, or OPEN.")

FAVOR <- zoo(t(apply(FAVOR, 1, function(v) ifelse(is.nan(v) | is.na(v), 0, v) )),
order.by = index(CLOSE))

# Step 2
K <- maxAssets
k <- 0
C <- rep(startingCash, times = nrow(CLOSE)) 
S <- names(CLOSE)
P <- p <- zoo( matrix(0, ncol=ncol(CLOSE), nrow=nrow(CLOSE)), order.by = index(CLOSE) )
if( !is.null( initP ) & !is.null( initp ) ){ 
P[1:maxLookback,] <- matrix(initP, ncol=length(initP), nrow=maxLookback, byrow = TRUE) 

p[1:maxLookback,] <- matrix(initp, ncol=length(initp), nrow=maxLookback, byrow = TRUE)
}
names(P) <- names(p) <- S
equity <- rep(NA, nrow(CLOSE))
rmNA <- pmax(unlist(lapply(FAVOR, equNA)), unlist(lapply(ENTRY, equNA)), unlist(lapply(EXIT, equNA)))

for( j in 1:ncol(ENTRY) ){ 
toRm <- rmNA[j]

if( toRm > (maxLookback + 1) & toRm < nrow(ENTRY) ){
    FAVOR[1:(toRm-1),j] <- NA
    ENTRY[1:(toRm-1),j] <- NA
    EXIT[1:(toRm-1),j] <- NA
}
}

# Step 3
for( i in maxLookback:(nrow(CLOSE)-1) ){

# Step 4
C[i+1] <- C[i]
P[i+1,] <- as.numeric(P[i,]) 
p[i+1,] <- as.numeric(p[i,])

longS <- S[which(P[i,] > 0)]
shortS <- S[which(P[i,] < 0)]
k <- length(longS) + length(shortS)

# Step 5
longTrigger <- setdiff(S[which(ENTRY[i,] == 1)], longS)
shortTrigger <- setdiff(S[which(ENTRY[i,] == -1)], shortS) 
trigger <- c(longTrigger, shortTrigger)

if( length(trigger) > K ) {
keepTrigger <- trigger[order(c(as.numeric(FAVOR[i,longTrigger]), -as.numeric(FAVOR[i,shortTrigger])), decreasing = TRUE)][1:K]

longTrigger <- longTrigger[longTrigger %in% keepTrigger] 
shortTrigger <- shortTrigger[shortTrigger %in% keepTrigger] 
trigger <- c(longTrigger, shortTrigger)
}

triggerType <- c(rep(1, length(longTrigger)), rep(-1, length(shortTrigger)))

# Step 6
longExitTrigger <- longS[longS %in% S[which(EXIT[i,] == 1 | EXIT[i,] == 999)]]

shortExitTrigger <- shortS[shortS %in% S[which(EXIT[i,] == -1 | EXIT[i,] == 999)]]

exitTrigger <- c(longExitTrigger, shortExitTrigger)

# Step 7
needToExit <- max( (length(trigger) - length(exitTrigger)) - (K - k), 0)

if( needToExit > 0 ){
toExitLongS <- setdiff(longS, exitTrigger) 
toExitShortS <- setdiff(shortS, exitTrigger)

toExit <- character(0)

for( counter in 1:needToExit ){
if( length(toExitLongS) > 0 & length(toExitShortS) > 0 ){
if( min(FAVOR[i,toExitLongS]) < min(-FAVOR[i,toExitShortS]) ){ 
pullMin <- which.min(FAVOR[i,toExitLongS])
toExit <- c(toExit, toExitLongS[pullMin])
toExitLongS <- toExitLongS[-pullMin]
} else {
pullMin <- which.min(-FAVOR[i,toExitShortS]) 
toExit <- c(toExit, toExitShortS[pullMin]) 
toExitShortS <- toExitShortS[-pullMin]
}

} else if( length(toExitLongS) > 0 & length(toExitShortS) == 0 ){
pullMin <- which.min(FAVOR[i,toExitLongS]) 
toExit <- c(toExit, toExitLongS[pullMin]) 
toExitLongS <- toExitLongS[-pullMin]

} else if( length(toExitLongS) == 0 & length(toExitShortS) > 0 ){ 
pullMin <- which.min(-FAVOR[i,toExitShortS])
toExit <- c(toExit, toExitShortS[pullMin])
toExitShortS <- toExitShortS[-pullMin]
} 
}
longExitTrigger <- c(longExitTrigger, longS[longS %in% toExit])
shortExitTrigger <- c(shortExitTrigger, shortS[shortS %in% toExit])
}
# Step 8
exitTrigger <- c(longExitTrigger, shortExitTrigger) 
exitTriggerType <- c(rep(1, length(longExitTrigger)), rep(-1, length(shortExitTrigger)))

# Step 9
if( length(exitTrigger) > 0 ){
for( j in 1:length(exitTrigger) ) {
exitPrice <- as.numeric(OPEN[i+1,exitTrigger[j]])

effectivePrice <- exitPrice * (1 - exitTriggerType[j] * slipFactor) -
      exitTriggerType[j] * (perShareCommission + spreadAdjust)

if( exitTriggerType[j] == 1 ){

C[i+1] <- C[i+1] + ( as.numeric( P[i,exitTrigger[j]] ) * effectivePrice ) - flatCommission

} else {
C[i+1] <- C[i+1] -
( as.numeric( P[i,exitTrigger[j]] ) * ( 2 * as.numeric(p[i, exitTrigger[j]]) - effectivePrice ) ) - flatCommission
}

P[i+1, exitTrigger[j]] <- 0
p[i+1, exitTrigger[j]] <- 0
k <- k - 1 
}
}

# Step 10
if( length(trigger) > 0 ){
for( j in 1:length(trigger) ){

entryPrice <- as.numeric(OPEN[i+1,trigger[j]])
effectivePrice <- entryPrice * (1 + triggerType[j] * slipFactor) + triggerType[j] * (perShareCommission + spreadAdjust)
P[i+1,trigger[j]] <- triggerType[j] * floor( ( (C[i+1] - flatCommission) / (K - k) ) / effectivePrice )
p[i+1,trigger[j]] <- effectivePrice
C[i+1] <- C[i+1] - ( triggerType[j] * as.numeric(P[i+1,trigger[j]]) * effectivePrice ) - flatCommission

k <- k + 1
} 
}

# Step 11
equity[i] <- C[i+1]
for( s in S[which(P[i+1,] > 0)] ){
equity[i] <- equity[i] + as.numeric(P[i+1,s]) * as.numeric(OPEN[i+1,s])
}

for( s in S[which(P[i+1,] < 0)] ){ 
equity[i] <- equity[i] - as.numeric(P[i+1,s]) *
( 2 * as.numeric(p[i+1,s]) - as.numeric(OPEN[i+1,s]) ) 
}

if( equity[i] < failThresh ){
warning("\n*** Failure Threshold Breached ***\n") 
break
}

# Step 12
if( verbose ){
if( i %% 21 == 0 ){
cat(paste0("################################## ", round(100 * (i - maxLookback) /
(nrow(CLOSE) - 1 - maxLookback), 1), "%", " ##################################\n"))
cat(paste("Date:\t",as.character(index(CLOSE)[i])), "\n") 
cat(paste0("Equity:\t", " $", signif(equity[i], 5), "\n")) 
cat(paste0("CAGR:\t ", round(100 * ((equity[i] / (equity[maxLookback]))^ (252/(i - maxLookback + 1)) - 1), 2), "%")) 
cat("\n")
cat("Assets:\t", S[P[i+1,] != 0])
cat("\n\n") 
}
} 
}
# Step 13
return(list(equity = equity, C = C, P = P, p = p)) 
}

