#LIBRARY
library(dplyr)
library(data.table)
#instal.packages('quantmod')
library(quantmod)
library(ggplot2)
library(scales)
#to drop 1st autocorrelation lag only
library(TSA)
#for ljung box
library(LSTS)
#Time series library for augmented dickey-fuller
library(tseries)
#Library for ARMA
library(forecast)
#To calculate RMSE
library(Metrics)
#==============================
#IMPORT DATASET
al.returns <- read.csv("/Users/siddharth/Desktop/Dissertation/Data/eikon/al_shfe_prices.csv")
View(al.returns)
#=============================
#PLOT CLOSING PRICE ALUMINIUM
al.returns$Date <- as.Date(al.returns$Date)
require(ggplot2)
ggplot(data = al.returns, aes(Date, CLOSE)) + ylab("Aluminium Closing Price") + geom_line(color = "#00AFBB") + theme_minimal() + scale_x_date(breaks = date_breaks("years"), labels = date_format("%y"))

#stat_smooth(color = "#FC4E07", fill = "#FC4E07", method = "loess")

#=============================
#Select variables of interest
alm <- subset(al.returns, select = c(Date, CLOSE))
#=============================
#Variable Transform To Returns
alm$returns <- Delt(alm$CLOSE)
#=============================
#Select New Variables
alm <- subset(alm, select = c(Date, returns))
#=============================
#Drop NAs
alm <- alm[-c(1),]
plot.ts(alm$returns)
#============================

#Plot autocorrelation function
#22 lags
acf(alm$returns, main = 'Autocorrelation - Aluminium Percentage Return on Closing Price', lag.max = 22, drop.lag.0 = TRUE)
# 252 lags (represents a year)
acf(alm$returns, main = 'Autocorrelation - Aluminium Percentage Return on Closing Price', lag.max = 252, drop.lag.0 = TRUE)
#============================
#Test for stationarity using Augmented Dickey-Fuller
adf.test(alm$returns, alternative = c("stationary"))
#Test for stationarity KPSS test.
kpss.test(alm$returns)
#============================
#Ljung Box Test for Lag 1
Box.test(alm$returns, lag = 1, type = c("Ljung-Box"), fitdf = 0)

#Plotting Ljung Box Test for Dataset
Box.Ljung.Test(alm$returns, lag = 2000)
#=============================
#Create lags
lag <- setDT(alm)[,paste0('return.lag', 1:22) := shift(alm$returns,1:22)]
#Drop NAs
lag <- na.omit(lag)

#===========================
#Plot Trend Line - Returns on Closing Price
ggplot(data = alm, aes(Date, returns)) + ylab("Aluminium Percentage Returns") + geom_line(color = "#00AFBB") + theme_minimal() + scale_x_date(breaks = date_breaks("years"), labels = date_format("%y")) + stat_smooth(color = "#FC4E07", fill = "#FC4E07", method = "loess")
#========================
#Auto ARIMA setup (Max lag that can be tested is 10)
arma.best <- auto.arima(alm$returns, seasonal = FALSE)
summary(arma.best)
#Check residuals
checkresiduals(arma.best)
#QQPlot
qqnorm(arma.best$residuals)
qqline(arma.best$residuals)
#=========================
#AR(1,0) model
#ar1_model <- auto.arima(alm$returns, seasonal = FALSE, max.Q = 0, max.q = 0, max.p = 1, max.P = 1, trace = TRUE)
#summary(ar1_model)
#Check residuals
#checkresiduals(ar1_model)
#===========================
#Best AR Model
ar_best <- auto.arima(alm$returns, seasonal = FALSE, max.Q = 0, max.q = 0, trace = TRUE)
summary(ar_best)
#Check residuals
checkresiduals(ar_best)
#=============================
#AR(0,0) model
#ar0_model <- auto.arima(alm$returns, seasonal = FALSE, max.Q = 0, max.q = 0, max.p = 0, max.P = 0, trace = TRUE)
#summary(ar0_model)
#Check residuals
#checkresiduals(ar0_model)
#==========================================
#Calculate RMSE white box model
mse(alm$returns, 0)
#Calculate RMSE mean model
mse(alm$returns, mean(alm$returns))
#========================
#Best ARIMA at higher residuals
#arma9_model <- auto.arima(alm$returns, seasonal = FALSE, max.Q = 9, max.q = 9, max.p = 9, max.P = 9, start.p = 9, start.P = 9, start.q = 9, start.Q = 9, trace = TRUE)
#=======================
#naive implementation
fit <- lm(returns ~ return.lag1 + return.lag2 + return.lag3 + return.lag4 + return.lag5 + return.lag6 + return.lag7 + return.lag8 + return.lag9 + return.lag10 + return.lag11 + return.lag12 + return.lag13 + return.lag14 + return.lag15 + return.lag16 + return.lag17 + return.lag18 + return.lag19 + return.lag20 + return.lag21 + return.lag22, data = lag )
mean(fit$residuals^2)

